import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@app/lib/components/navbar";
import { FileDropzoneProvider } from "@app/lib/contexts/fileDropzoneContext";
import Footer from "@app/lib/components/footer";
import LayoutContainer from "@app/lib/components/layoutContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen">
          <FileDropzoneProvider>
            <Navbar />

            <main className="flex-1 container py-8 mx-auto">
              <LayoutContainer>{children}</LayoutContainer>
            </main>
            <Footer />
          </FileDropzoneProvider>
        </div>
      </body>
    </html>
  );
}
